name: Build Binary

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Binary
      run: |
        docker build -t builder .
        docker run --rm -v ${PWD}:/project builder make
    - uses: actions/upload-artifact@v3
      with:
        name: Button_Break.rpx
        path: "*.rpx"
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: Button_Break.wuhb
        path: "*.wuhb"
        if-no-files-found: error

